#!/usr/bin/env perl
use warnings;
use strict;

my $ARCH = $ENV{ARCH};
if (!defined $ARCH) {
    print "apinit: ARCH is not set\n";
    exit -1;
}

system "./buildlist.$ARCH";
system "cp apsymbols.h.$ARCH apsymbols.h";


